const BB_BLENDS = [
  {
    key: 'bedtime', accent: 'bedtime',
    name: ['Banana', 'Bedtime Tea'],
    subtitle: ['A gentle, calming blend', 'for restful nights'],
    about: 'A soothing, naturally sweet blend designed to relax the body and quiet the mind. Perfect to unwind with before bed and support a deep, restful sleep.',
    ingredients: ['Banana', 'Banana Peel', 'Chamomile', 'Cinnamon Bark', 'Vanilla Bean'],
    benefits: ['Supports restful sleep', 'Calms the nervous system', 'Aids digestion', 'Naturally sweet & comforting'],
    quote: ['Sip slow. Dream deep.'],
    titleColor: 'var(--ink-900)',
    band: 'var(--wheat-400)', bandInk: 'var(--ink-900)',
    frame: 'color-mix(in srgb, var(--bark-500) 55%, transparent)',
    margins: ['margin-bedtime-left.png', 'margin-bedtime-right.png'],
  },
  {
    key: 'sunset', accent: 'sunset',
    name: ['Egyptian', 'Sunset'],
    subtitle: ['A floral, fruity blend', 'to uplift & inspire'],
    about: 'A vibrant, exotic blend inspired by golden evenings. Beautifully floral and refreshing, it uplifts the senses and transports you to a state of calm clarity and joy.',
    ingredients: ['Hibiscus', 'Blue Lotus', 'Rose Petals', 'Orange Peel'],
    benefits: ['Uplifts mood', 'Supports emotional balance', 'Rich in antioxidants', 'Naturally caffeine free'],
    quote: ['Breathe in beauty.', 'Sip in the sunset.'],
    titleColor: 'var(--wine-800)',
    band: 'var(--wine-band)', bandInk: 'var(--paper-100)',
    frame: 'color-mix(in srgb, var(--wine-700) 42%, transparent)',
    margins: ['margin-sunset-left.png', 'margin-sunset-right.png'],
  },
  {
    key: 'wildwood', accent: 'wildwood',
    name: ['Wildwood', 'Elixir'],
    subtitle: ['An earthy, herbal blend', 'for vitality & balance'],
    about: "A grounding, nourishing blend of wild herbs to support your body's natural defences, soothe the digestive system and restore inner balance.",
    ingredients: ['Nettle', 'Peppermint', 'Cats Claw', 'Licorice Root', 'Ginger Root'],
    benefits: ['Supports immunity', 'Aids digestion', 'Anti-inflammatory', 'Energising & grounding'],
    quote: ['Rooted in nature.', 'Made for you.'],
    titleColor: 'var(--moss-900)',
    band: 'var(--moss-500)', bandInk: 'var(--paper-100)',
    frame: 'color-mix(in srgb, var(--moss-700) 45%, transparent)',
    margins: ['margin-wildwood-left.png', 'margin-wildwood-right.png'],
  },
];
Object.assign(window, { BB_BLENDS });
